Repository TeamSaifu/Saifu_Flutter, pull requests merged in 2021-07, with the labels that each got.

#13 SIF-21 予算設定画面を作成
  .idea/Saifu_Flutter.iml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/budget.dart
  lib/main.dart
  pubspec.lock
Labels: Medium

#14 SIF-43 ショートカット編集画面のレイアウト作成
  lib/main.dart
  lib/shortcut.dart
  lib/shortcut_model.dart
Labels: Small

#15 SIF-17 ホーム画面のレイアウトの作成
  lib/home.dart
  lib/main.dart
  lib/shortcut_model.dart
  pubspec.yaml
Labels: Large

#17 SIF-51 広告を表示できるようにした
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/main.dart
  pubspec.yaml
Labels: Small

#16 SIF-49 ショートカットモデルの型を変更
  lib/setting.dart
  lib/shortcut.dart
  lib/shortcut_model.dart
Labels: Medium

#18 Alpha-1ブランチへ結合してテスト
  .gitignore
  .idea/Saifu_Flutter.iml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: Extra Large
